### ISSUE TITLE
Frame offsets like in offsets.txt to Friday Night Funkin, pls?

### ISSUE THREAD

**Issue by kubapl2004gmail** [TheWilley/Fruity_Dance_Sprite_Sheet_Generator#30]
Frame offsets like in offsets.txt to Friday Night Funkin, pls?

**Comment by TheWilley** [comment]
Hi! I'm sadly not familiar with Friday Night Funkin nor the `offset.txt` you do mention, can you elaborate please?

**Comment by kubapl2004gmail** [comment]
> Hi! I'm sadly not familiar with Friday Night Funkin nor the `offset.txt` you do mention, can you elaborate please?
Offsets for each individual frame, pls?

**Comment by kubapl2004gmail** [comment]
Offsets x and y for each individual frame, pls?

**Comment by TheWilley** [comment]
Hi! I'm sorry for not responding, as other things have been a priority.

You already can change each individual frame offset, simply click on an image and once selected change the offset using the arrow symbols, like in this video:
![Recording 2023-05-11 at 13 04 14](https://github.com/TheWilley/Fruity_Dance_Sprite_Sheet_Generator/assets/89783791/eec482a1-659d-48ab-96a6-08b31ad5a151)
